name: "Mi CICD workflow"
on:
  push:
    branches:
      - main
jobs:
  build-test:
    run-on: ubuntu-latest
    step:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm test